// Remote console config for bootstrapping a running multinode sandbox.
canton {
  remote-participants {
    participant1 {
      ledger-api.address = "127.0.0.1"
      ledger-api.port = 5011
      admin-api.address = "127.0.0.1"
      admin-api.port = 5012
    }
    participant2 {
      ledger-api.address = "127.0.0.1"
      ledger-api.port = 5021
      admin-api.address = "127.0.0.1"
      admin-api.port = 5022
    }
  }

  remote-sequencers {
    sequencer1 {
      public-api.address = "127.0.0.1"
      public-api.port = 5001
      admin-api.address = "127.0.0.1"
      admin-api.port = 5002
    }
  }

  remote-mediators {
    mediator1 {
      admin-api.address = "127.0.0.1"
      admin-api.port = 5202
    }
  }
}
